DefaultContentLanguage: "en"
title: "Digital Bangkok Recorder"
theme: "hextra"
relativeurls: true

params:
  custom_css: 
  - "css/custom.css"
  table_css:
  - "css/bkkrec_table_eng.css"
  custom_js: []
  hideAuthor: false
  since: 2016
  name: "Mark Hollow"
  author: "Mark Hollow"
  navbar:
    displayTitle: true
    displayLogo: true
    logo:
      path: /images/logo.svg
      dark: /images/logo-dark.svg
      link: /
      width: 20
      height: 20
  theme:
    default: hextra
    displayToggle: true
  footer:
    # change copyright msg in i18n/footer.yaml
    displayPoweredBy: true
    displayCopyright: true
  page:
    # full (100%), wide (90rem), normal (1280px)
    width: wide

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
  - name: Articles
    url: /articles
    weight: 1
  - name: Publications
    url: /publications
    weight: 2